version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_USER: superset
    volumes:
      - mysql:/var/lib/mysql
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
       - superset
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  mysql:
  redis:
